import { writable } from 'svelte/store';

const locationData = writable([
  {
    officeLocation: 'Franklin',
    street: '702 15th Avenue',
    poBox: 'P.O. Box 207',
    city: 'Franklin',
    state: 'NE',
    zip: '68939',
    phone: '(308) 425-6273',
    fax: '(308) 425-6274',
    email: 'duncanjelkin@yahoo.com',
    imgUrl: './images/franklinOffice.jpg',
    mapUrl: 'http://g.co/maps/8zsb7',
  },
  {
    officeLocation: 'Oxford',
    street: '325 Ogden Street',
    poBox: 'P.O. Box 67',
    city: 'Oxford',
    state: 'NE',
    zip: '68967',
    phone: '(308) 824-3231',
    fax: '(308) 824-3692',
    email: 'ddwnlaw@yahoo.com',
    imgUrl: './images/oxfordOffice.jpg',
    mapUrl: 'http://g.co/maps/wxw83',
  },
  {
    officeLocation: 'Alma',
    street: '616 W Main Street',
    poBox: 'P.O. Box 528',
    city: 'Alma',
    state: 'NE',
    zip: '68920',
    phone: '(308) 928-2165',
    fax: '(308)-928-2166',
    email: 'duncanjelkin@yahoo.com',
    imgUrl: './images/almaOffice.jpg',
    mapUrl: 'http://g.co/maps/2hbxx',
  },
  {
    officeLocation: 'Hildreth',
    street: '144 Commercial Avenue',
    poBox: 'P.O. Box 340',
    city: 'Hildreth',
    state: 'NE',
    zip: '68947',
    phone: '(308) 938-4585',
    fax: '(308) 938-3014',
    email: 'ddjwlaw@yahoo.com',
    imgUrl: './images/hildrethOffice.jpg',
    mapUrl: 'http://g.co/maps/dw7ev',
  },
]);

export default locationData;
